config/routes.rb
Mashthis::Application.routes.draw do
  resources :songs

  root 'songs#index'

  

end

app/models/song.rb
class Song < ActiveRecord::Base
  def rel
    if self.key > 0 and self.key < 4
      return self.key*-1 - 9
    elsif self.key >= 4
      return self.key*-1 + 3
    elsif self.key < 0 and self.key > -10
      return self.key*-1 + 3
    elsif self.key <= -10
      return self.key*-1 - 9
    else 
      return "Error"
    end
  end
  
  SCALE = {
    1 => "A", 
    2 => "Bb", 
    3 => "B",
    4 => "C",
    5 => "Db",
    6 => "D",
    7 => "Eb",
    8 => "E",
    9 => "F",
    10 => "Gb",
    11 => "G",
    12 => "Ab",
    -1 => "Am",
    -2 => "Bbm",
    -3 => "Bm",
    -4 => "Cm",
    -5 => "C#m",
    -6 => "Dm",
    -7 => "Ebm",
    -8 => "Em",
    -9 => "Fm",
    -10 => "F#m",
    -11 => "Gm",
    -12 => "G#m"
    }
  
  def scale
    return SCALE[self.key]
  end
  
  def scale_rel
    return SCALE[self.rel]
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy]

  # GET /songs
  # GET /songs.json
  def index
    @songs = Song.all
    @count = Song.count
    @song = Song.new
  end

  # GET /songs/1
  # GET /songs/1.json
  def show
  end

  # GET /songs/new
  def new
    @song = Song.new
  end

  # GET /songs/1/edit
  def edit
  end

  # POST /songs
  # POST /songs.json
  def create
    @song = Song.new(song_params)

    respond_to do |format|
      if @song.save
        format.html { redirect_to @song, notice: 'Song was successfully created.' }
        format.json { render action: 'show', status: :created, location: @song }
      else
        format.html { render action: 'new' }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /songs/1
  # PATCH/PUT /songs/1.json
  def update
    respond_to do |format|
      if @song.update(song_params)
        format.html { redirect_to @song, notice: 'Song was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    @song.destroy
    respond_to do |format|
      format.html { redirect_to songs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song
      @song = Song.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def song_params
      params.require(:song).permit(:title, :artist, :albumtitle, :prodyear, :bpm, :key)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mashthis</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/songs/_form.html.erb
<%= form_for(@song) do |f| %>
  <% if @song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
      <% @song.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :artist %><br>
    <%= f.text_field :artist %>
  </div>
  <div class="field">
    <%= f.label :albumtitle %><br>
    <%= f.text_field :albumtitle %>
  </div>
  <div class="field">
    <%= f.label :prodyear %><br>
    <%= f.number_field :prodyear %>
  </div>
  <div class="field">
    <%= f.label :bpm %><br>
    <%= f.number_field :bpm %>
  </div>
  <div class="field">
    <%= f.label :key %><br>
    <%= f.number_field :key %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/songs/edit.html.erb
<h1>Editing song</h1>

<%= render 'form' %>

<%= link_to 'Show', @song %> |
<%= link_to 'Back', songs_path %>

app/views/songs/index.html.erb
<h1>Listing songs</h1>

<p> Total Songs: <%= @count %> </p>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Artist</th>
      <th>Albumtitle</th>
      <th>Prodyear</th>
      <th>Bpm</th>
      <th>Key</th>
      <th>Relative</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @songs.each do |song| %>
      <tr>
        <td><%= song.title %></td>
        <td><%= song.artist %></td>
        <td><%= song.albumtitle %></td>
        <td><%= song.prodyear %></td>
        <td><%= song.bpm %></td>
        <td><%= song.scale %></td>
        <td><%= song.scale_rel %></td>
        <td><%= link_to 'Show', song %></td>
        <td><%= link_to 'Edit', edit_song_path(song) %></td>
        <td><%= link_to 'Destroy', song, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<h1>New song</h1>

<%= render 'form' %>

app/views/songs/new.html.erb
<h1>New song</h1>

<%= render 'form' %>

<%= link_to 'Back', songs_path %>

app/views/songs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @song.title %>
</p>

<p>
  <strong>Artist:</strong>
  <%= @song.artist %>
</p>

<p>
  <strong>Albumtitle:</strong>
  <%= @song.albumtitle %>
</p>

<p>
  <strong>Prodyear:</strong>
  <%= @song.prodyear %>
</p>

<p>
  <strong>Bpm:</strong>
  <%= @song.bpm %>
</p>

<p>
  <strong>Key:</strong>
  <%= @song.scale %>
</p>

<p>
  <strong>Relative:</strong>
  <%= @song.scale_rel %>
</p>

<p>
  <% if @song.bpm > 100 %>
  Fast song
  <% else %>
  Slow song
  <% end %>

<%= link_to 'Edit', edit_song_path(@song) %> |
<%= link_to 'Back', songs_path %>